#!/usr/bin/env bash
# scripts/apply-core-path.sh — point `echobird_core` at a local checkout
# so `cargo tauri build` works on a fork without push access to the
# private `EchoBird-secret-` repo.
#
# Usage:
#   export ECHOBIRD_CORE_PATH=/abs/path/to/echobird_core-local
#   scripts/apply-core-path.sh          # patch Cargo.toml + write .cargo/config.toml
#   cargo tauri build                   # now uses the local checkout
#   scripts/apply-core-path.sh unset    # revert both files
#
# What it does to src-tauri/Cargo.toml:
#   Appends a [patch."https://github.com/edison7009/EchoBird-secret-.git"]
#   block overriding `echobird_core = { path = "$ECHOBIRD_CORE_PATH" }`.
#   This is the standard Cargo way to redirect a git dep to a path
#   without editing the actual `echobird_core = { git = ... }` line.
#
# What it does to src-tauri/.cargo/config.toml:
#   Writes a tiny config that maps the upstream git URL to a local
#   "vendored" source name. The vendored source itself is empty (no
#   crates) — we only use it as a stable name for the [patch] block
#   to resolve against. This file is gitignored by the upstream
#   project (.cargo/ is excluded), so it's strictly local.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CARGO_TOML="$REPO_ROOT/src-tauri/Cargo.toml"
CARGO_CONFIG_DIR="$REPO_ROOT/src-tauri/.cargo"
CARGO_CONFIG="$CARGO_CONFIG_DIR/config.toml"
MARKER="# >>> ECHOBIRD_CORE_PATH OVERRIDE — managed by scripts/apply-core-path.sh"

write_local_cargo_config() {
  mkdir -p "$CARGO_CONFIG_DIR"
  cat > "$CARGO_CONFIG" <<TOML
# Local override for the private \`echobird_core\` crate.
# Generated by scripts/apply-core-path.sh — safe to delete; the
# upstream project gitignores this path anyway.

[source."https://github.com/edison7009/EchoBird-secret-.git"]
replace-with = "echobird-core-local"

[source.echobird-core-local]
# The actual path override lives in [patch."..."] in
# src-tauri/Cargo.toml; this block just needs a stable source
# name for Cargo to bind the [patch] entry to.
TOML
}

unset_override() {
  # Strip the [patch] block from Cargo.toml
  if grep -qF "$MARKER" "$CARGO_TOML"; then
    python3 - "$CARGO_TOML" <<'PY'
import sys
path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    src = f.read()
marker = "# >>> ECHOBIRD_CORE_PATH OVERRIDE — managed by scripts/apply-core-path.sh"
idx = src.find(marker)
if idx >= 0:
    new = src[:idx].rstrip() + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(new)
PY
    echo "Reverted $CARGO_TOML to use the upstream git dep."
  else
    echo "No ECHOBIRD_CORE_PATH override in $CARGO_TOML — nothing to unset."
  fi
  # Remove the local .cargo/config.toml
  if [[ -f "$CARGO_CONFIG" ]]; then
    rm "$CARGO_CONFIG"
    rmdir "$CARGO_CONFIG_DIR" 2>/dev/null || true
    echo "Removed $CARGO_CONFIG."
  fi
}

case "${1:-}" in
  unset)
    unset_override
    exit 0
    ;;
  "")
    if [[ -z "${ECHOBIRD_CORE_PATH:-}" ]]; then
      cat >&2 <<USAGE
Usage:
  export ECHOBIRD_CORE_PATH=/abs/path/to/echobird_core-local
  scripts/apply-core-path.sh          # rewrite Cargo.toml to use that path
  scripts/apply-core-path.sh unset    # revert to the upstream git dep

ECHOBIRD_CORE_PATH is currently empty.
USAGE
      exit 1
    fi
    ;;
  *)
    echo "Unknown argument: $1" >&2
    exit 1
    ;;
esac

if [[ ! -d "$ECHOBIRD_CORE_PATH" ]]; then
  echo "ECHOBIRD_CORE_PATH=$ECHOBIRD_CORE_PATH does not exist or is not a directory." >&2
  exit 1
fi

if [[ ! -f "$ECHOBIRD_CORE_PATH/Cargo.toml" ]]; then
  echo "ECHOBIRD_CORE_PATH=$ECHOBIRD_CORE_PATH does not contain a Cargo.toml —" >&2
  echo "is this really the echobird_core checkout?" >&2
  exit 1
fi

# Always start clean: strip any prior override first.
unset_override >/dev/null

# Append the [patch] block.
cat >> "$CARGO_TOML" <<TOML

$MARKER
# Auto-generated when ECHOBIRD_CORE_PATH is set. Do not edit by hand;
# re-run \`scripts/apply-core-path.sh unset\` to drop this block.
[patch."https://github.com/edison7009/EchoBird-secret-.git"]
echobird_core = { path = "$ECHOBIRD_CORE_PATH" }
TOML

# Write the local .cargo/config.toml so Cargo knows the source name.
write_local_cargo_config

echo "Patched $CARGO_TOML to use echobird_core from $ECHOBIRD_CORE_PATH"
echo "Run \`cargo tauri build\` to verify, or \`scripts/apply-core-path.sh unset\` to revert."
